import React from "react";
import image from "../assets/aibanner.png";

const HeroBanner = () => {
  return (
    <section className="bg-base-200 max-w-5xl m-auto rounded-xl">
      <div className="container flex flex-col justify-center p-6 mx-auto sm:py-12 lg:py-24 lg:flex-row lg:justify-between">
        <div className="flex items-center justify-center p-6 mt-8 lg:mt-0 h-72 sm:h-80 lg:h-96 xl:h-112 2xl:h-128">
          <img
            src={image}
            alt=""
            className="object-contain h-72 sm:h-80 lg:h-96 xl:h-112 2xl:h-128"
          />
        </div>
        <div className="flex flex-col justify-center p-6 text-center rounded-sm lg:max-w-md xl:max-w-lg lg:text-left">
          <h1 className="text-4xl font-bold sm:text-6xl">
            <span className="text-base-content  "> MidJourney </span>
            <span className="text-primary">2.0</span>
          </h1>
          <p className="mt-6 mb-8 text-lg sm:mb-12 text-neutral">
            Browse through a collection of imaginative and visaully stunning
            images generated by <span className="text-primary">DALL-E-AI</span>
          </p>
        </div>
      </div>
    </section>
  );
};

export default HeroBanner;
